apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-variant-autoscaler-wva-saturation-scaling-config
  labels:
    app.kubernetes.io/instance: workload-variant-autoscaler
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/managed-by: Helm
data:
  default: |
    kvCacheThreshold: 0.8
    queueLengthThreshold: 5
    kvSpareTrigger: 0.1
    queueSpareTrigger: 3
