{{- if and .Values.controller.enabled .Values.wva.prometheus.caCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workload-variant-autoscaler.clusterResourceName" . }}-prometheus-ca
  namespace: {{ .Values.wva.prometheus.monitoringNamespace }}
  labels:
    {{- include "workload-variant-autoscaler.labels" . | nindent 4 }}
data:
  ca.crt: |
{{ .Values.wva.prometheus.caCert | indent 4 }}
{{- end }}
